version: 0.0
os: linux
files:
  - source: /
    destination: /app/voice/exos-voice-verimetricsy/
    overwrite: true
hooks:
  BeforeInstall:
  - location: scripts/beforeInstall.sh
    timeout: 60
  AfterInstall:
  - location: scripts/afterInstall.sh
    timeout: 60
  ApplicationStop:
  - location: scripts/stop_server.sh
    timeout: 60
  ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 60
  ValidateService:
  - location: scripts/validate_server.sh
    timeout: 60

