version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - pwd
      - npm install
      - node verimetrics.js
      - pwd
artifacts:
  files:
    - appspec.yml
    - scripts/start_server.sh
    - scripts/stop_server.sh
    - scripts/validate_server.sh
    - scripts/afterInstall.sh
